package kernel_test

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	oerrors "github.com/open-platform-model/library/opm/errors"
	"github.com/open-platform-model/library/opm/internal/registrytest"
	"github.com/open-platform-model/library/opm/internal/schematest"
	"github.com/open-platform-model/library/opm/kernel"
	"github.com/open-platform-model/library/opm/schema"
)

// The base catalog whose contracts the provider catalog implements. It is
// never served: a provider implements contracts ANOTHER catalog defines, and
// the transformer's demand entry carries the contract value, so the fixture
// needs the FQNs and not the defining artifact.
const baseCatalogPath = "test.example/catalogs/base"

func backupTraitFQN() string  { return baseCatalogPath + "/traits/backup@v1" }
func containerResFQN() string { return baseCatalogPath + "/resources/container@v1" }

// providerCatalogBody renders the body of a catalog whose single transformer
// requires one provider-fulfilled trait and one ordinary catalog-fulfilled
// resource. It is authored rather than generated by registrytest.BuildCatalog
// because that helper authors no `fulfilment`, which is the whole subject
// here: every generated demand takes core's "catalog" default.
func providerCatalogBody(path, version string) string {
	major, _, _ := strings.Cut(version, ".")
	impl := fmt.Sprintf("%s/transformers/schedule@%s", path, version)
	return fmt.Sprintf(`metadata: {
	modulePath:  %q
	version:     %q
	description: "test provider catalog"
}
#transformers: %q: {
	kind: "ComponentTransformer"
	metadata: {
		name:        "schedule"
		description: "schedule transformer"
		fqn:         %q
	}
	requiredTraits: %q: {
		kind: "Trait"
		metadata: {
			name:           "backup"
			modulePath:     %q
			apiVersion:     "v1"
			catalogVersion: "1.0.0"
			fqn:            %q
		}
		fulfilment: "provider"
		optional:   bool | *false
		spec: backup: _
		appliesTo: []
	}
	requiredResources: %q: {
		kind: "Resource"
		metadata: {
			name:           "container"
			modulePath:     %q
			apiVersion:     "v1"
			catalogVersion: "1.0.0"
			fqn:            %q
		}
		spec: container: _
	}
	#transform: output: {}
}
`,
		path+"@v"+major, version,
		impl, impl,
		backupTraitFQN(), baseCatalogPath+"/traits", backupTraitFQN(),
		containerResFQN(), baseCatalogPath+"/resources", containerResFQN(),
	)
}

// writeCatalogDir lays out a one-package CUE module holding body after the
// bare `c.#Catalog` line and returns its root. Core resolves from the shared
// workspace cache.
func writeCatalogDir(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "cue.mod"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "cue.mod", "module.cue"), fmt.Appendf(nil,
		"module: \"test.example/catalogs/provider@v1\"\nlanguage: version: \"v0.17.0\"\ndeps: \"opmodel.dev/core@v2\": v: %q\n",
		registrytest.DefaultCoreVersion), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "catalog.cue"), fmt.Appendf(nil,
		"package provider\n\nimport c \"opmodel.dev/core@v2\"\n\nc.#Catalog\n%s", body), 0o644))
	return dir
}

// writeRawDir lays out a one-package CUE module whose file is exactly body,
// with no core import: the refusal cases need no schema to be refused by the
// shape gate.
func writeRawDir(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "cue.mod"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "cue.mod", "module.cue"), []byte(
		"module: \"test.example/raw@v1\"\nlanguage: version: \"v0.17.0\"\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "artifact.cue"), fmt.Appendf(nil,
		"package raw\n\n%s", body), 0o644))
	return dir
}

// listTree returns every path under dir, sorted, so a test can assert the
// caller's directory was not written to.
func listTree(t *testing.T, dir string) []string {
	t.Helper()
	var out []string
	require.NoError(t, filepath.Walk(dir, func(path string, _ os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		out = append(out, rel)
		return nil
	}))
	sort.Strings(out)
	return out
}

// catalog-acquisition spec, "Catalog acquisition from a registry and from a
// directory", registry scenario: a published catalog is acquired by path and
// version through the kernel's mapping, comes back with its package evaluated
// and its source stamped, and both derivations answer off it.
//
// The negative case runs FIRST, before any positive load: CUE serves a
// coordinate from the module cache before it consults any registry, so once a
// positive acquisition has cached the served catalog, a kernel without the
// mapping would find it there and prove nothing.
func TestKernel_AcquireCatalogFromRegistry(t *testing.T) {
	path := registrytest.UniquePath(t, "provider")
	const version = "1.0.0"
	mapping := registrytest.NewCatalogRegistry(t, registrytest.CatalogFixture{
		Path: path, Version: version, Body: providerCatalogBody(path, version),
	})
	// Route the served prefix only through the option under test.
	t.Setenv("CUE_REGISTRY", schema.PublicRegistry)
	ctx := context.Background()

	t.Run("a kernel without the mapping cannot resolve the coordinate", func(t *testing.T) {
		cat, err := kernel.New().AcquireCatalogFromRegistry(ctx, path+"@v1", "v"+version)
		require.Error(t, err)
		assert.Nil(t, cat)
	})

	k := kernel.New(kernel.WithRegistry(mapping))
	cat, err := k.AcquireCatalogFromRegistry(ctx, path+"@v1", "v"+version)
	require.NoError(t, err)

	require.NotNil(t, cat.Metadata)
	assert.Equal(t, path+"@v1", cat.Metadata.ModulePath)
	assert.Equal(t, version, cat.Metadata.Version)
	assert.True(t, cat.Package.Exists())

	require.NotNil(t, cat.Source, "the source is stamped, so Requires needs no second fetch")
	assert.NotEmpty(t, cat.Source.Overlay, "a fetched catalog is staged in overlay mode")

	provides, err := cat.Provides()
	require.NoError(t, err)
	assert.Equal(t, []string{backupTraitFQN()}, provides,
		"the provider-fulfilled trait is derived; the catalog-fulfilled resource is not")

	requires, err := cat.Requires()
	require.NoError(t, err)
	assert.Equal(t, registrytest.DefaultCoreVersion, requires["opmodel.dev/core@v2"])
}

// catalog-acquisition spec, "A non-catalog artifact is refused by shape",
// module scenario, over the REGISTRY path: the refusal is the shape gate's,
// so it reads the same whichever route resolved the artifact.
func TestKernel_AcquireCatalogFromRegistry_RefusesAModule(t *testing.T) {
	modPath := registrytest.UniquePath(t, "modules/hello")
	mapping := registrytest.NewModuleRegistry(t, []registrytest.ModuleFixture{{
		Path: modPath, Version: "0.0.2",
		File: registrytest.BuildModuleFile("hello", "hello", modPath+"@v0", ""),
	}}, nil)

	cat, err := kernel.New(kernel.WithRegistry(mapping)).
		AcquireCatalogFromRegistry(context.Background(), modPath+"@v0", "v0.0.2")

	require.Error(t, err)
	assert.Nil(t, cat, "no partial catalog is returned")
	assert.ErrorIs(t, err, oerrors.ErrWrongKind)
	assert.Contains(t, err.Error(), `"Catalog"`, "the expected kind is named")
	assert.Contains(t, err.Error(), `"Module"`, "the found kind is named")
}

// catalog-acquisition spec, "Catalog acquisition from a registry and from a
// directory", directory scenario.
func TestKernel_AcquireCatalogFromDir(t *testing.T) {
	schematest.SetEnv(t)
	dir := writeCatalogDir(t, providerCatalogBody("test.example/catalogs/provider", "1.0.0"))
	before := listTree(t, dir)

	cat, err := kernel.New().AcquireCatalogFromDir(context.Background(), dir)
	require.NoError(t, err)

	require.NotNil(t, cat.Metadata)
	assert.Equal(t, "test.example/catalogs/provider@v1", cat.Metadata.ModulePath)
	assert.Equal(t, "1.0.0", cat.Metadata.Version)

	require.NotNil(t, cat.Source)
	assert.Equal(t, dir, cat.Source.Root)
	assert.NotEmpty(t, cat.Source.Overlay, "the directory peer stamps overlay mode too")

	provides, err := cat.Provides()
	require.NoError(t, err)
	assert.Equal(t, []string{backupTraitFQN()}, provides)

	requires, err := cat.Requires()
	require.NoError(t, err)
	assert.Equal(t, registrytest.DefaultCoreVersion, requires["opmodel.dev/core@v2"],
		"Requires answers identically whichever route acquired the catalog")

	assert.Equal(t, before, listTree(t, dir), "the caller's directory is not written to")
}

// catalog-acquisition spec, "A non-catalog artifact is refused by shape": every
// gate failure wraps the shared sentinel and returns no partial catalog. Each
// case asserts the sentinel rather than the message, so the wording is free to
// change.
func TestKernel_AcquireCatalogFromDir_RefusesNonCatalogs(t *testing.T) {
	schematest.SetEnv(t)
	tests := []struct {
		name string
		body string
		want error
	}{
		{
			name: "a module artifact claimed as a catalog",
			body: `kind: "Module"
metadata: {
	name:       "hello"
	modulePath: "test.example/modules/hello@v0"
	version:    "0.0.2"
}`,
			want: oerrors.ErrWrongKind,
		},
		{
			name: "an artifact carrying no kind",
			body: `metadata: {
	modulePath: "test.example/catalogs/provider@v1"
	version:    "1.0.0"
}`,
			want: oerrors.ErrWrongKind,
		},
		{
			name: "a kind that is not a concrete string",
			body: `kind: string
metadata: {
	modulePath: "test.example/catalogs/provider@v1"
	version:    "1.0.0"
}`,
			want: oerrors.ErrWrongKind,
		},
		{
			name: "a catalog missing the identity the gate requires",
			body: `kind: "Catalog"
metadata: modulePath: "test.example/catalogs/provider@v1"`,
			want: oerrors.ErrMissingRequiredField,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeRawDir(t, tt.body)

			cat, err := kernel.New().AcquireCatalogFromDir(context.Background(), dir)

			require.Error(t, err)
			assert.Nil(t, cat, "no partial catalog is returned on any gate failure")
			assert.True(t, errors.Is(err, tt.want), "wraps %v, got: %v", tt.want, err)
		})
	}
}
