// Package synth builds an OPM #ModuleInstance CUE value from in-memory typed
// inputs by unifying caller-supplied identity (name, namespace, module
// reference, values, labels, annotations) against the schema definition
// resolved through the caller-supplied *schema.Cache.
//
// It covers exactly one artifact: synth.Instance builds a #ModuleInstance
// from a *module.Module plus typed identity and values. There is no platform
// synthesis: a platform is a CUE module on disk that imports its catalogs
// (enhancement 0019 D5/D6), generated by the frontend and acquired with
// (*kernel.Kernel).AcquirePlatformFromDir.
//
// Synth is a peer of opm/helper/loader, not a subpackage of it. The loader
// tree (opm/helper/loader/file, opm/helper/loader/registry) reads existing
// artifacts from a source — filesystem or registry. Synthesis is
// creation from typed inputs: there is no file to parse, no bytes to decode.
// Co-locating synth under loader would conflate verbs and force every reader
// to ignore the package doc when interpreting the package path. Keeping them
// as peers makes each verb legible at a glance.
//
// Recommended entry point: (*kernel.Kernel).SynthesizeInstance, which chains
// synth.Instance into Kernel.ProcessModuleInstance so a caller building an
// instance from typed inputs gets a fully validated, concrete
// *module.Instance in one call. Call synth.Instance directly only when there
// is no *Kernel on hand (rare; mostly unit-testing in tight loops).
//
// Single-build construction (ADR-003): synth.Instance does NOT stitch an instance
// value together from separate CUE evaluations. It synthesizes a virtual CUE
// package — a fabricated cue.mod/module.cue (deps: the resolved core version +
// the module's path@version), an instance.cue that IMPORTS the module and writes
// `#module: <import>` plus caller metadata, and a values.cue rendered from the
// caller's Values via format.Node — and evaluates it in one build through the
// same loader build-and-shape-gate step LoadInstancePackage uses for on-disk
// packages. There is no cue.Scope/userModule trick and no Go-side
// FillPath(#config, Values) pre-merge: because the module enters the build by
// import (one #Image / #Secret closure), the schema's own
// `unifiedModule = #module & {#config: values}` performs the values merge in
// CUE. The synth and authored-Instance paths therefore share one mechanism, so a
// render bug surfaces in both or neither. See
// adr/003-no-cross-build-fillpath-into-closed-values.md.
//
// Schema source of truth: the synth helper never reimplements derivations the
// CUE schema already owns (instance UUID stamping, components fan-out from
// #components, auto-secrets injection, standard label stamping). Every derived
// field flows through unification with the artifact definition obtained from
// in.SchemaCache.Get(ctx); the schema package itself is resolved by the Cache's
// underlying Loader (typically schema.OCILoader against CUE_REGISTRY).
//
// Boundary scope: synth lives under opm/helper/ because it is an opinionated
// frontend convenience. Frontends MAY bypass it and unify against the schema
// themselves; nothing in synth is part of the kernel contract.
package synth
