// Package synth builds an OPM #ModuleInstance CUE value from typed in-memory
// inputs: caller-supplied identity (name, namespace, values, labels,
// annotations) against a module the caller already acquired with its staged
// source.
//
// It covers exactly one artifact. There is no platform synthesis: a platform
// is a CUE module on disk that imports its catalogs (enhancement 0019 D5/D6),
// generated by the frontend and acquired with
// (*kernel.Kernel).AcquirePlatformFromDir.
//
// It lives under opm/internal/ so it stays off the library's public SemVer
// surface: [Kernel.SynthesizeInstance] is the one synthesis entry point, and
// it owns the *cue.Context, the schema cache and the registry mapping this
// package is handed. The dependency edge runs synth -> loader (synthesis
// builds THROUGH [loader.LoadDir]); loader never imports synth.
//
// Single-build construction (ADR-006): [Instance] does NOT stitch an instance
// value together from separate CUE evaluations. It synthesizes a virtual CUE
// package inside the module's own staged tree — an instance.cue that IMPORTS
// the module and writes `#module: <import>` plus caller metadata, and a
// values.cue rendered from the caller's merged values via format.Node — and
// evaluates it in one build through the same build-and-shape-gate step a
// directory-acquired instance package runs. There is no cue.Scope/userModule
// trick and no Go-side FillPath(#config, Values) pre-merge: because the module
// enters the build by import (one #Image / #Secret closure), the schema's own
// `unifiedModule = #module & {#config: values}` performs the values merge in
// CUE. The synthesized and authored paths therefore share one mechanism, so a
// render bug surfaces in both or neither. See
// adr/006-single-build-artifact-construction.md.
//
// Schema source of truth: this package never reimplements derivations the CUE
// schema already owns (instance UUID stamping, components fan-out from
// #components, auto-secrets injection, standard label stamping). Every derived
// field flows through unification with the artifact definition the module's
// own cue.mod/module.cue resolves; the caller supplies only the core version
// the synthesized import's major is derived from.
package synth

import (
	"fmt"
	"maps"
	"path/filepath"

	"cuelang.org/go/cue"

	oerrors "github.com/open-platform-model/library/opm/errors"
	"github.com/open-platform-model/library/opm/internal/loader"
	"github.com/open-platform-model/library/opm/internal/valuesfile"
	"github.com/open-platform-model/library/opm/module"
)

// Input is the typed input carried into [Instance]. Required fields: Module
// (source-carrying), Name, Namespace. Optional fields are filled into the
// instance only when present (non-nil / non-empty / non-zero); empty values do
// not displace schema-derived fields.
//
// It carries no schema cache and no *cue.Context: the kernel owns both and
// hands this package the resolved core version and its own context.
type Input struct {
	// Module is the source #Module the instance deploys. Required. Its
	// metadata.modulePath / metadata.version identify the published module
	// the synthesized package imports (Instance references the module by
	// import, not by inlining its value), and its staged source is the tree
	// the synthesized package is built inside.
	Module *module.Module

	// Name is the instance name (metadata.name). Required. Must satisfy the
	// schema's #NameType regex; violations surface as a CUE unification error
	// from Instance.
	Name string

	// Namespace is the target namespace (metadata.namespace). Required.
	Namespace string

	// Values is the merged configuration value unified against the module's
	// #config. The zero cue.Value signals "no values supplied" — the schema's
	// values path is left unfilled and concreteness is enforced downstream by
	// Kernel.SynthesizeInstance. Instance NEVER falls back to
	// Module.debugValues; that is a frontend policy concern.
	Values cue.Value

	// Labels and Annotations layer over the schema's stamped
	// module-instance.opmodel.dev/{name,uuid} labels. CUE unification merges
	// caller-supplied entries with schema-stamped ones; caller-supplied keys
	// MUST NOT collide with the schema's reserved keys.
	Labels      map[string]string
	Annotations map[string]string

	// Env is the environment slice the synthesized build's load configuration
	// consults — the kernel's CUE_REGISTRY mapping via cueenv.Override, nil to
	// read the process environment unchanged. It is kernel plumbing, not a
	// caller-facing knob: Kernel.SynthesizeInstance fills it from WithRegistry.
	Env []string
}

// synthPkgDir is the reserved subdirectory, under the acquired module's staged
// root, that the synthesized instance package is overlaid into. It is a single
// non-"_"-prefixed segment so CUE does not treat it as an ignored directory and
// it cannot collide with a real module package. The instance is loaded from
// this subdirectory while the module's own root (and its cue.mod/module.cue)
// remains the build's module root.
const synthPkgDir = "opm-synth-instance"

// Instance builds a #ModuleInstance CUE value by synthesizing an in-memory CUE
// package INSIDE the acquired module's own staged source tree and evaluating it
// in a single build (ADR-006), through the same [loader.LoadDir]
// build-and-shape-gate path a directory-acquired instance package runs. The
// module's own (already-tidied at publish time) cue.mod/module.cue is the
// build's module file, so it — not a fabricated dep list — drives transitive
// dependency resolution. The synthesized package consists of an instance.cue
// overlaid under a reserved subdirectory of the module root (importing core and
// the module's own package, writing `#module: <import>` plus caller-supplied
// metadata) and — when Values is supplied — a values.cue rendered from it.
//
// Because the module is the build's main module, its own package import resolves
// LOCALLY (no fabricated dependency, no registry round-trip for the module
// itself), and the module's transitive imports (core, catalog subpackages, …)
// resolve through the module's own cue.mod/module.cue. This is why a module that
// imports a catalog subpackage synthesizes correctly where the previous
// fabricated-{core, module}-deps approach failed (library#31). The module enters
// the build by import, so there is no closed-into-closed FillPath and no Go-side
// value pre-merge: the schema's own `let unifiedModule = #module & {#config:
// values}` performs the values merge in CUE.
//
// coreVersion is the core release the caller's schema cache resolved; only its
// major selects the synthesized package's core import. The concrete core
// version the import resolves to comes from the module's own
// cue.mod/module.cue (design D4), never from this argument.
//
// Instance REQUIRES the module to carry staged source (Module.HasSource());
// acquire it via Kernel.AcquireModuleFromRegistry or
// Kernel.AcquireModuleFromDir. It never fetches from a registry itself.
//
// The function does NOT enforce concreteness and does NOT decode instance
// metadata. Both live downstream in the kernel's instance processing, which
// Kernel.SynthesizeInstance chains onto this call (the values merge against
// #config happens inside the build).
//
// The returned cue.Value carries every schema-derived field automatically:
// metadata.uuid is computed by uuid.SHA1, components is fanned from the
// unified module, opm-secrets is added when #Secret instances are present,
// and the standard module-instance.opmodel.dev/{name,uuid} labels are stamped.
// Instance stamps only the caller-supplied fields and lets CUE derive the rest.
//
// Alongside the value, Instance returns the staged tree the build evaluated:
// Root is the module's staged root, Pkg the reserved instance subdirectory,
// Overlay the module's cloned overlay augmented with the synthesized files
// (instance.cue, plus values.cue when Values was supplied). The overlay is the
// clone the build used, never the module's own map, so the caller may retain
// it and the module may be synthesized again. Kernel.SynthesizeInstance stamps
// it onto the resulting Instance.Source. Every error path returns a nil tree.
func Instance(cueCtx *cue.Context, coreVersion string, in Input) (cue.Value, *module.Source, error) {
	// Module, Name, Namespace and the staged source are checked by
	// Kernel.SynthesizeInstance too, and deliberately so: this function
	// dereferences Module.Metadata and Module.Source, so it states its own
	// preconditions rather than trusting its one caller to have stated them.
	// The duplication is a guard, not drift — both sides wrap the same
	// opm/errors sentinel, so which one fires is invisible to a consumer.
	if in.Module == nil {
		return cue.Value{}, nil, oerrors.ErrMissingModule
	}
	if in.Name == "" {
		return cue.Value{}, nil, oerrors.ErrMissingName
	}
	if in.Namespace == "" {
		return cue.Value{}, nil, oerrors.ErrMissingNamespace
	}
	if coreVersion == "" {
		return cue.Value{}, nil, fmt.Errorf("%w: resolved core schema version unavailable, cannot derive synth core import major", oerrors.ErrSchemaUnavailable)
	}
	if in.Module.Metadata == nil || in.Module.Metadata.ModulePath == "" || in.Module.Metadata.Version == "" {
		return cue.Value{}, nil, fmt.Errorf("%w: module has no modulePath/version identity to import by", oerrors.ErrMissingModule)
	}
	if !in.Module.HasSource() {
		return cue.Value{}, nil, oerrors.ErrMissingSource
	}

	moduleRoot, overlay, err := buildOverlay(in, coreVersion)
	if err != nil {
		return cue.Value{}, nil, fmt.Errorf("instance synthesis: %w", err)
	}

	// Evaluate the synthesized package through the SAME build-and-shape-gate
	// step a directory-acquired instance runs; the instance package lives in a
	// subdirectory of the module's staged root, with the module's own
	// cue.mod/module.cue as the module file.
	val, err := loader.LoadDir(cueCtx, moduleRoot, "./"+synthPkgDir, overlay, in.Env, loader.InstanceSpec)
	if err != nil {
		return cue.Value{}, nil, fmt.Errorf("instance synthesis: %w", err)
	}
	return val, &module.Source{Root: moduleRoot, Pkg: synthPkgDir, Overlay: overlay}, nil
}

// buildOverlay clones the acquired module's staged overlay and adds the
// synthesized instance package's files (instance.cue, and values.cue when Values
// is supplied) under the reserved synthPkgDir subdirectory of the module's
// staged root. It returns the module root (the load.Config.ModuleRoot, so the
// module's own cue.mod/module.cue governs the build) and the augmented overlay.
//
// The module's overlay is cloned, never mutated, so a module value can be
// synthesized more than once.
func buildOverlay(in Input, coreVersion string) (string, map[string][]byte, error) {
	src := in.Module.Source
	overlay := maps.Clone(src.Overlay)

	pkgRoot := filepath.Join(src.Root, synthPkgDir)
	overlay[filepath.Join(pkgRoot, "instance.cue")] = []byte(renderInstanceFile(in, coreVersion))

	// values.cue is rendered through the renderer shared with the kernel's
	// extra-values acquire path (opm/internal/valuesfile): canonical CUE via
	// format.Node on the value's syntax, never string-interpolated. A missing
	// Values yields no file, so the schema's values path stays open and
	// concreteness is enforced downstream by Kernel.SynthesizeInstance.
	valuesSrc, err := valuesfile.Render("instance", in.Values)
	if err != nil {
		return "", nil, err
	}
	if valuesSrc != nil {
		overlay[filepath.Join(pkgRoot, "values.cue")] = valuesSrc
	}

	return src.Root, overlay, nil
}
